# Generated by Django 2.1.2 on 2018-11-02 14:21

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('cuartos', models.IntegerField()),
                ('aseos', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), srid=4326)),
                ('empresario', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
