# Generated by Django 2.1.2 on 2018-11-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasador_app', '0003_auto_20181102_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='location',
        ),
    ]
