# Generated by Django 2.1.2 on 2018-11-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador_app', '0004_remove_inmueble_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='distrito',
            field=models.CharField(choices=[('ancón', 'Ancón'), ('ate', 'Ate'), ('barranco', 'Barranco'), ('bellavista', 'Bellavista'), ('breña', 'Breña'), ('callao', 'Callao'), ('carabayllo', 'Carabayllo'), ('carmen de la legua', 'Carmen de la Legua'), ('chaclacayo', 'Chaclacayo'), ('chorrillos', 'Chorrillos'), ('chosica', 'Chosica'), ('cieneguilla', 'Cieneguilla'), ('comas', 'Comas'), ('el agustino', 'El Agustino'), ('independencia', 'Independencia'), ('jesus maria', 'Jesús María'), ('la molina', 'La Molina'), ('la perla', 'La Perla'), ('la punta', 'La Punta'), ('la victoria', 'La Victoria'), ('lima', 'Cercado de Lima'), ('lince', 'Lince'), ('los olivos', 'Los Olivos'), ('lurin', 'Lurín'), ('magdalena del mar', 'Magdalena del Mar'), ('mi peru', 'Mi Perú'), ('miraflores', 'Miraflores'), ('pachacamac', 'Pachacamac'), ('pucusana', 'Pucusana'), ('pueblo libre', 'Pueblo Libre'), ('puente piedra', 'Puente Piedra'), ('punta hermosa', 'Punta Hermosa'), ('punta negra', 'Punta Negra'), ('rimac', 'Rimac'), ('san bartolo', 'San Bartolo'), ('san borja', 'San Borja'), ('san isidro', 'San Isidro'), ('san juan de lurigancho', 'San Juan de Lurigancho'), ('san juan de miraflores', 'San Juan de Miraflores'), ('san luis', 'San Luis'), ('san martin de porres', 'San Martín de Porres'), ('san miguel', 'San Miguel'), ('santa anita', 'Santa Anita'), ('santa maria del mar', 'Santa María del Mar'), ('santa rosa', 'Santa Rosa'), ('santiago de surco', 'Santiago de Surco'), ('surquillo', 'Surquillo'), ('ventanilla', 'Ventanilla'), ('villa el salvador', 'Villa el Salvador'), ('villa maria del triunfo', 'Villa María del Triundo')], default='Escoge distrito', max_length=100),
        ),
    ]
