# Generated by Django 2.1.2 on 2018-11-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador_app', '0006_auto_20181106_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='distrito',
            field=models.CharField(choices=[('ancón', 'Ancon'), ('ate', 'Ate'), ('barranco', 'Barranco'), ('breña', 'Breña'), ('carabayllo', 'Carabayllo'), ('lima', 'Cercado de Lima'), ('chaclacayo', 'Chaclacayo'), ('chorrillos', 'Chorrillos'), ('chosica', 'Chosica'), ('cieneguilla', 'Cieneguilla'), ('comas', 'Comas'), ('el agustino', 'El Agustino'), ('jesus maria', 'Jesus Maria'), ('la molina', 'La Molina'), ('la victoria', 'La Victoria'), ('lince', 'Lince'), ('los olivos', 'Los Olivos'), ('lurin', 'Lurin'), ('magdalena del mar', 'Magdalena del Mar'), ('miraflores', 'Miraflores'), ('pachacamac', 'Pachacamac'), ('pucusana', 'Pucusana'), ('pueblo libre', 'Pueblo Libre'), ('puente piedra', 'Puente Piedra'), ('punta hermosa', 'Punta Hermosa'), ('punta negra', 'Punta Negra'), ('rimac', 'Rimac'), ('san bartolo', 'San Bartolo'), ('san borja', 'San Borja'), ('san isidro', 'San Isidro'), ('san juan de lurigancho', 'San Juan de Lurigancho'), ('san juan de miraflores', 'San Juan de Miraflores'), ('san luis', 'San Luis'), ('san martin de porres', 'San Martin de Porres'), ('san miguel', 'San Miguel'), ('santa anita', 'Santa Anita'), ('santa maria del mar', 'Santa Maria del Mar'), ('santa rosa', 'Santa Rosa'), ('santiago de surco', 'Santiago de Surco'), ('surquillo', 'Surquillo'), ('villa el salvador', 'Villa el Salvador'), ('villa maria del triunfo', 'Villa María del Triundo')], default='Escoge distrito', max_length=100),
        ),
    ]
