# Generated by Django 2.1.2 on 2018-11-06 17:18

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasador_app', '0008_auto_20181106_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-77.0282, -12.0432, srid=4326), srid=4326),
        ),
    ]
