# Generated by Django 2.1.2 on 2018-11-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador_app', '0009_inmueble_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='distrito',
            field=models.CharField(choices=[('Ancon', 'Ancon'), ('Ate', 'Ate'), ('Barranco', 'Barranco'), ('Breña', 'Breña'), ('Carabayllo', 'Carabayllo'), ('Cercado de Lima', 'Cercado de Lima'), ('Chaclacayo', 'Chaclacayo'), ('Chorrillos', 'Chorrillos'), ('Chosica', 'Chosica'), ('Comas', 'Comas'), ('El Agustino', 'El Agustino'), ('Jesus Maria', 'Jesus Maria'), ('La Molina', 'La Molina'), ('La Victoria', 'La Victoria'), ('Lince', 'Lince'), ('Los Olivos', 'Los Olivos'), ('Lurin', 'Lurin'), ('Magdalena del Mar', 'Magdalena del Mar'), ('Miraflores', 'Miraflores'), ('Pueblo libre', 'Pueblo Libre'), ('Punta Hermosa', 'Punta Hermosa'), ('Rimac', 'Rimac'), ('San Bartolo', 'San Bartolo'), ('San Borja', 'San Borja'), ('San Isidro', 'San Isidro'), ('San Juan de Lurigancho', 'San Juan de Lurigancho'), ('San Juan de Miraflores', 'San Juan de Miraflores'), ('San Luis', 'San Luis'), ('San Martin de Porres', 'San Martin de Porres'), ('San Miguel', 'San Miguel'), ('Santa Maria del Mar', 'Santa Maria del Mar'), ('Santiago de Surco', 'Santiago de Surco'), ('Surquillo', 'Surquillo')], default='Escoge distrito', max_length=100),
        ),
    ]
