# Generated by Django 2.1.2 on 2018-11-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasador_app', '0012_auto_20181108_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='aseos',
            new_name='baños',
        ),
    ]
