# Generated by Django 2.1.2 on 2018-11-19 16:41

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasador_app', '0014_auto_20181116_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(choices=[('Ancon', 'Ancon'), ('Ate', 'Ate'), ('Barranco', 'Barranco'), ('Bellavista', 'Bellavista'), ('Breña', 'Breña'), ('Callao', 'Callao'), ('Carabayllo', 'Carabayllo'), ('Carmen De La Legua Reynoso', 'Carmen De La Legua Reynoso'), ('Cercado de Lima', 'Cercado de Lima'), ('Chaclacayo', 'Chaclacayo'), ('Chorrillos', 'Chorrillos'), ('Chosica', 'Chosica'), ('Cieneguilla', 'Cieneguilla'), ('Comas', 'Comas'), ('El Agustino', 'El Agustino'), ('Independencia', 'Independencia'), ('Jesus Maria', 'Jesus Maria'), ('La Molina', 'La Molina'), ('La Perla', 'La Perla'), ('La Victoria', 'La Victoria'), ('Lince', 'Lince'), ('Los Olivos', 'Los Olivos'), ('Lurin', 'Lurin'), ('Magdalena del Mar', 'Magdalena del Mar'), ('Miraflores', 'Miraflores'), ('Pachacamac', 'Pachacamac'), ('Pucusana', 'Pucusana'), ('Pueblo Libre', 'Pueblo Libre'), ('Puente Piedra', 'Puente Piedra'), ('Punta Hermosa', 'Punta Hermosa'), ('Punta Negra', 'Punta Negra'), ('Rimac', 'Rimac'), ('San Bartolo', 'San Bartolo'), ('San Borja', 'San Borja'), ('San Isidro', 'San Isidro'), ('San Juan de Lurigancho', 'San Juan de Lurigancho'), ('San Juan de Miraflores', 'San Juan de Miraflores'), ('San Luis', 'San Luis'), ('San Martin de Porres', 'San Martin de Porres'), ('San Miguel', 'San Miguel'), ('Santa Anita', 'Santa Anita'), ('Santa Maria del Mar', 'Santa Maria del Mar'), ('Santa Rosa', 'Santa Rosa'), ('Santiago de Surco', 'Santiago de Surco'), ('Surquillo', 'Surquillo'), ('Ventanilla', 'Ventanilla'), ('Villa El Salvador', 'Villa El Salvador'), ('Villa Maria del Triunfo', 'Villa Maria del Triunfo')], default='Escoge distrito', max_length=100)),
                ('area', models.IntegerField()),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-77.0282, -12.0432, srid=4326), srid=4326)),
                ('empresario', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='casa',
            name='distrito',
            field=models.CharField(choices=[('Ancon', 'Ancon'), ('Ate', 'Ate'), ('Barranco', 'Barranco'), ('Bellavista', 'Bellavista'), ('Breña', 'Breña'), ('Callao', 'Callao'), ('Carabayllo', 'Carabayllo'), ('Cercado de Lima', 'Cercado de Lima'), ('Chaclacayo', 'Chaclacayo'), ('Chorrillos', 'Chorrillos'), ('Chosica', 'Chosica'), ('Cieneguilla', 'Cieneguilla'), ('Comas', 'Comas'), ('El Agustino', 'El Agustino'), ('Independencia', 'Independencia'), ('Jesus Maria', 'Jesus Maria'), ('La Molina', 'La Molina'), ('La Perla', 'La Perla'), ('La Punta', 'La Punta'), ('La Victoria', 'La Victoria'), ('Lince', 'Lince'), ('Los Olivos', 'Los Olivos'), ('Lurin', 'Lurin'), ('Magdalena del Mar', 'Magdalena del Mar'), ('Miraflores', 'Miraflores'), ('Pachacamac', 'Pachacamac'), ('Pucusana', 'Pucusana'), ('Pueblo Libre', 'Pueblo Libre'), ('Puente Piedra', 'Puente Piedra'), ('Punta Hermosa', 'Punta Hermosa'), ('Punta Negra', 'Punta Negra'), ('Rimac', 'Rimac'), ('San Bartolo', 'San Bartolo'), ('San Borja', 'San Borja'), ('San Isidro', 'San Isidro'), ('San Juan de Lurigancho', 'San Juan de Lurigancho'), ('San Juan de Miraflores', 'San Juan de Miraflores'), ('San Luis', 'San Luis'), ('San Martin de Porres', 'San Martin de Porres'), ('San Miguel', 'San Miguel'), ('Santa Anita', 'Santa Anita'), ('Santa Maria del Mar', 'Santa Maria del Mar'), ('Santa Rosa', 'Santa Rosa'), ('Santiago de Surco', 'Santiago de Surco'), ('Surquillo', 'Surquillo'), ('Ventanilla', 'Ventanilla'), ('Villa El Salvador', 'Villa El Salvador'), ('Villa Maria del Triunfo', 'Villa Maria del Triunfo')], default='Escoge distrito', max_length=100),
        ),
    ]
