# Generated by Django 2.1.2 on 2018-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador_app', '0015_auto_20181119_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='cuartos',
            new_name='dormitorios',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='cuartos',
            new_name='dormitorios',
        ),
        migrations.AlterField(
            model_name='casa',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='area',
            field=models.FloatField(),
        ),
    ]
